FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY tailwindcss.js /usr/share/nginx/html/tailwindcss.js
COPY marked.min.js /usr/share/nginx/html/marked.min.js
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
